name: Lambda CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Zip each Lambda function
      - name: Zip Lambda Functions
        run: |
          zip -j GetAlbums.zip my_lambda_functions/GetAlbums/index.py
          zip -j GetAlbumsByYear.zip my_lambda_functions/GetAlbumsByYear/index.py

      # Step 3: Upload the zipped files to S3
      - name: Upload Zipped Files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp GetAlbums.zip s3://${{ secrets.AWS_S3_BUCKET }}/GetAlbums.zip
          aws s3 cp GetAlbumsByYear.zip s3://${{ secrets.AWS_S3_BUCKET }}/GetAlbumsByYear.zip

      # Step 4: Update Lambda functions to use the new code from S3
      - name: Update Lambda Functions
        run: |
          aws lambda update-function-code --function-name GetAlbums \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --s3-key GetAlbums.zip

          aws lambda update-function-code --function-name GetAlbumsByYear \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --s3-key GetAlbumsByYear.zip
